### PR TITLE
Update core

### PR DESCRIPTION
**Pull request by dandavison**
Update core to https://github.com/temporalio/sdk-core/commit/8691fed95ffa1ea220ccb29b67acead76c116336

### CODE REVIEW

**Comment by cretz** [comment]
May have to upgrade tonic and tonic build (probably just a `cargo update` to update all deps in the lock would do it, probably don't need toml change)

**Review by cretz — APPROVED** [review]

**Comment by cretz** [comment]
> I agree. I think this PR should be the first PR post-release, rather than the last PR pre-release.

:+1: It would have been nice to get https://github.com/temporalio/sdk-core/issues/818 and https://github.com/temporalio/sdk-core/pull/815 and some others in this release, but I understand that reviewing this core change may take longer than we're wanting for some pure Python changes pending release.

**Comment by Sushisource** [comment]
My intention was that this upgrade should also include the changes to avoid applying jobs in different sets and thus match the behavior mentioned in https://github.com/temporalio/sdk-python/issues/606

Having all the SDKs work the same way in that regard will be a long term win I think, and is in general just a bit simpler to think about.

**Comment by cretz** [comment]
@dandavison - can you do a `cargo update` to help solve #671?

**Comment by cretz** [comment]
(added #671 as being closed by this)

**Pull request closed without merging**
