### PR TITLE
downgrade to protobuf 3 to satisfy temporary workaround

### PR DESCRIPTION
**Pull request by jeremy-cho-skydio**
## What was changed
This PR essentially reverts the protobuf 4 upgrade changes that were merged into main as part of https://github.com/temporalio/sdk-python/pull/136. The intent of this PR is to create a workaround for projects that incur unresolvable package dependency issues caused by the upgrade and is NOT meant to be merged into main.

Relevant Slack thread in Temporal Slack community: https://temporalio.slack.com/archives/CTT84RS0P/p1667336466199119

## Why?
`temporalio==0.1b2` introduced some nice changes like the testing module but also upgrades the protobuf dependency to `protobuf < 4.22, >= 4.21` which can cause issues in existing projects that utilize packages that don't support protobuf 4. As a workaround, this PR downgrades the protobuf package and attempts to create a wheel that includes the 0.1b2 changes excluding the protobuf upgrade.

## Checklist

1. This PR doesn't close any issues but the relevant issue to track this is https://github.com/temporalio/sdk-python/issues/181

3. How was this tested:
As long as CI passes I think we're good?

4. Any docs updates needed?
None needed I believe

### CODE REVIEW

**Comment by cretz** [comment]
Approving to run. This made more changes than just the proto downgrade.

**Comment by jeremy-cho-skydio** [comment]
Yep, thanks for pointing that out @cretz I'm still in the process of grooming the changes will poke you when I feel like it's ready

**Comment by jeremy-cho-skydio** [comment]
Okay I think it's in a state now where at least the files touched are the same as the update PR. Lines changed still look a little different but :man_shrugging:

**Comment by cretz** [comment]
See https://github.com/temporalio/sdk-python/pull/215 where I have added proto 3 support back into the library

**Comment by cretz** [comment]
@jeremy-cho-skydio - with proto 3 and proto 4 now both supported in the latest release, can we close this?

**Comment by cretz** [comment]
Closing PR. Can reopen if needed.

**Pull request closed without merging**
